version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
  db:
    container_name: docker-toturial-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - '5432:5432'
    volumes:
      - ~/.docker-volumns/docker-toturial-db:/var/lib/postgresql/data
  api:
    container_name: docker-toturial-api  
    build:
      context: .
      dockerfile: web-api/Dockerfile
    image: web-api:v1.0
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


